[[services]]
name = "backend"
dockerfilePath = "Dockerfile"
healthcheckPath = "/api/auth"

[[services]]
name = "frontend"
dockerfilePath = "frontend/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
